# -*- coding: utf-8 -*-
"""ingest_chicago.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vxzmZQnphd5-_QSGN0UzVuPELCEuMn0C
"""

import os
import requests
import pandas as pd

def ensure_dir(path):
    os.makedirs(path, exist_ok=True)

DATA_DIR = os.path.join("..", "data_raw", "chicago")
# Example: Chicago Crimes dataset (via Chicago Data Portal API, CSV export)
CHICAGO_CRIME_CSV = "https://data.cityofchicago.org/api/views/pk66-w54g/rows.csv?accessType=DOWNLOAD"
def download_chicago_crime():
    ensure_dir(DATA_DIR)
    url = CHICAGO_CRIME_CSV
    print("Downloading Chicago crime dataset")
    resp = requests.get(url, stream=True)
    resp.raise_for_status()
    out_path = os.path.join(DATA_DIR, "chicago_crime.csv")
    with open(out_path, "wb") as f:
        for chunk in resp.iter_content(chunk_size=8192):
            f.write(chunk)
    print("Saved to", out_path)
    return out_path

def load_chicago_crime(csv_path=None):
    if csv_path is None:
        csv_path = os.path.join(DATA_DIR, "chicago_crime.csv")
    df = pd.read_csv(csv_path, low_memory=False, sep=',', on_bad_lines='skip')
    print(f"Loaded {len(df)} records from Chicago crime data.")
    return df

if __name__ == "__main__":
    path = download_chicago_crime()
    df = load_chicago_crime(path)
    print(df.columns.tolist())
    print(df.head())