# -*- coding: utf-8 -*-
"""ingest_gdelt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fAHu0kT4saiPUxJy06cNGVRfkT872EeV
"""

import torch
from torch.utils.data import Dataset
from torchvision import datasets
from torchvision.transforms import ToTensor
import matplotlib.pyplot as plt
import os
import requests
import zipfile
import io
import pandas as pd

def ensure_dir(path):
    if not os.path.exists(path):
        os.makedirs(path)

# Directory to store GDELT data
DATA_DIR = os.path.join("..", "data_raw", "gdelt")

# Example: download one day’s GDELT event CSV (adjust date as you like)
GDELT_BASE = "https://data.gdeltproject.org/events/"
GDELT_FILE = "20251130.export.CSV.zip"  # change to desired date

def download_gdelt(date_filename=GDELT_FILE):
    ensure_dir(DATA_DIR)
    url = GDELT_BASE + date_filename
    print("Downloading", url)
    # Disabling SSL verification due to SSLCertVerificationError.
    # Use with caution and only for trusted sources, as it reduces security.
    resp = requests.get(url, stream=True, verify=False)
    resp.raise_for_status()
    with zipfile.ZipFile(io.BytesIO(resp.content)) as z:
        # extract to DATA_DIR
        z.extractall(DATA_DIR)
    print("Downloaded and extracted to", DATA_DIR)

def load_gdelt_into_df(filename=None):
    if filename is None:
        # find first .CSV file in DATA_DIR
        files = [f for f in os.listdir(DATA_DIR) if f.endswith(".CSV")]
        if not files:
            raise FileNotFoundError("No GDELT CSV found in " + DATA_DIR)
        filename = os.path.join(DATA_DIR, files[0])
    df = pd.read_csv(filename, sep='\t', header=None, dtype=str, low_memory=False)
    print(f"Loaded {len(df)} rows from GDELT event data.")
    return df

if __name__ == "__main__":
    download_gdelt()
    df = load_gdelt_into_df()
    print(df.head())