# -*- coding: utf-8 -*-
"""pytorch_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LRoetIqNfPdFfB6Rqd0F5HnIXC0Op7tw
"""

import torch
import torch.nn as nn

class SimpleMLP(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        super(SimpleMLP, self).__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, output_dim)
        )

    def forward(self, x):
        return self.net(x)

# Example usage
if __name__ == "__main__":
    model = SimpleMLP(10, 20, 1)
    x = torch.randn(5, 10)
    print(model(x))